preprocessing:
  change_type_columns:
    district: category
    area: category
    metro: category
    transport_type: category
  drop_columns: ["house", "street"]
  train_path: ../data/raw/cian_data.json
  unique_values_path: ../data/processed/unique_values.json
  all_values_path: ../data/processed/all_values.json
  train_path_proc: ../data/processed/train.json
  test_path_proc: ../data/processed/test.json
  test_size: 0.2
  val_size: 0.16
  target_column: price
  random_state: 10

train:
  n_trials: 10
  n_folds: 5
  random_state: 10
  target_column: price
  model_path: ../models/model_lgb.joblib
  study_path: ../models/study.joblib
  metrics_path: ../report/metrics.json
  params_path: ../report/best_params.json

evaluate:
  predict_path: ../data/check/test.json

endpoints:
  train: 'http://fastapi:8000/train'
  prediction_input: 'http://fastapi:8000/predict_input'
  prediction_from_file: 'http://fastapi:8000/predict'

#  train: 'http://localhost:8000/train'
#  prediction_input: 'http://localhost:8000/predict_input'
#  prediction_from_file: 'http://localhost:8000/predict'
